"""
Django settings for eshop_mp4 project.
Generated by 'django-admin startproject' using Django 4.2.11.
"""

from pathlib import Path
import os
import dj_database_url


if os.path.exists("env.py"):
    import env  # noqa

# --- Core ---
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = False  # set False in production

ALLOWED_HOSTS = [
    '.herokuapp.com',
    '8000-mariusgeorge-cimp4-9n6d5n7aela.ws.codeinstitute-ide.net',
    '127.0.0.1',
    'localhost',
]

CSRF_TRUSTED_ORIGINS = [
    'https://eshop-mp4-502a44cdcfd1.herokuapp.com',
]

# --- Apps ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'crispy_forms',
    'crispy_bootstrap4',
    'storages',

    # local
    'store',
    'stripe',
]

# --- Middleware ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eshop_mp4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.menu_links',
                'store.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'eshop_mp4.wsgi.application'

# --- Databases ---

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "radio_claim_crate_697599",
        "USER": "neondb_owner",
        "PASSWORD": "npg_9waGhtg7VEpD",
        "HOST": "ep-shiny-frost-a2322ygi.eu-central-1.aws.neon.tech",
        "PORT": "5432",
        "OPTIONS": {"sslmode": "require"},
    }
}



# if os.environ.get("DATABASE_URL"):
    
#     DATABASES["postgres"] = dj_database_url.parse(os.environ["DATABASE_URL"], conn_max_age=600, ssl_require=True)

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- I18N ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Static & Media ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # <- fixed name (was STATICFILES)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'media')

# WhiteNoise static file storage (good for production; safe in dev too)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- AWS S3 (optional, guarded by env) ---
if 'USE_AWS' in os.environ:
    AWS_S3_OBJECT_PARAMETERS = {
        'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
        'CacheControl': 'max-age=94608000',
    }
    AWS_STORAGE_BUCKET_NAME = 'eshop-mp4'
    AWS_S3_REGION_NAME = 'eu-north-1'
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

    STATICFILES_STORAGE = 'custom_storages.StaticStorage'
    STATICFILES_LOCATION = 'static'
    DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'
    MEDIAFILES_LOCATION = 'media'

    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATICFILES_LOCATION}/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIAFILES_LOCATION}/'

# --- Crispy Forms ---
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# --- Security ---
# In dev with DEBUG=True, using secure cookies can block local auth over http.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # helpful on Heroku/Reverse proxies

# --- Stripe (consider moving to env vars) ---
STRIPE_PUBLISHABLE_KEY = 'pk_test_51PBax6RrQAMRXLE9m9jHNwcDCcHVtLOtHMJetBUCFuReVwZgb3i2a53EJKXNsucSgwfxJDDDmtwTXoS1EBsZIObS00xBCxFsGW'
STRIPE_SECRET_KEY = 'sk_test_51PBax6RrQAMRXLE9YP2pEc62zuZK3aWR7cd8qqtJa2WU4uDrf4ooPjcaBQLuI65DUkhTiQ1Y55BC3Mzt7usXhQSL00IrNS52P9'

# --- Defaults ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
